/// Maps the local `normalizedTitle` to the Bolls.life API `bookid`.
/// Bolls.life uses sequential IDs: 1-39 for Old Testament, 40-66 for New Testament.
const Map<String, int> bookIdMapping = {
  // Velho Testamento
  'genesis': 1,
  'exodo': 2,
  'levitico': 3,
  'numeros': 4,
  'deuteronomio': 5,
  'josue': 6,
  'juizes': 7,
  'rute': 8,
  '1samuel': 9,
  '2samuel': 10,
  '1reis': 11,
  '2reis': 12,
  '1cronicas': 13,
  '2cronicas': 14,
  'esdras': 15,
  'neemias': 16,
  'ester': 17,
  'jo': 18,
  'salmos': 19,
  'proverbios': 20,
  'eclesiastes': 21,
  'cantares': 22,
  'isaias': 23,
  'jeremias': 24,
  'lamentacoes': 25,
  'ezequiel': 26,
  'daniel': 27,
  'oseias': 28,
  'joel': 29,
  'amos': 30,
  'obadias': 31,
  'jonas': 32,
  'miqueias': 33,
  'naum': 34,
  'habacuque': 35,
  'sofonias': 36,
  'ageu': 37,
  'zacarias': 38,
  'malaquias': 39,
  // Novo Testamento
  'mateus': 40,
  'marcos': 41,
  'lucas': 42,
  'joao': 43,
  'atos': 44,
  'romanos': 45,
  '1corintios': 46,
  '2corintios': 47,
  'galatas': 48,
  'efesios': 49,
  'filipenses': 50,
  'colossenses': 51,
  '1tessalonicenses': 52,
  '2tessalonicenses': 53,
  '1timoteo': 54,
  '2timoteo': 55,
  'tito': 56,
  'filemon': 57,
  'hebreus': 58,
  'tiago': 59,
  '1pedro': 60,
  '2pedro': 61,
  '1joao': 62,
  '2joao': 63,
  '3joao': 64,
  'judas': 65,
  'apocalipse': 66,
};

/// Returns the Bolls.life bookId for a given normalizedTitle.
/// Returns null if the book is not found.
int? getBookId(String normalizedTitle) {
  return bookIdMapping[normalizedTitle];
}
